# Generated by Django 5.0.8 on 2024-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='slugfield',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
